use_frameworks!

platform :ios, '15.0'

target 'Example' do
  pod 'AD_SwiftUI', :path => '../'
  
  #pod 'SwiftMesh'
  pod 'TradPlusAdSDK/AdMobAdapter', '9.7.0'
  pod 'Google-Mobile-Ads-SDK','10.8.0'
  pod 'TradPlusAdSDK/AppLovinAdapter', '9.7.0'
  pod 'AppLovinSDK','11.11.1'
  pod 'TradPlusAdSDK/MintegralAdapter', '9.7.0'
  pod 'MintegralAdSDK' ,'7.4.1'
  pod 'MintegralAdSDK/All','7.4.1'
  pod 'TradPlusAdSDK/SigmobAdapter', '9.7.0'
  pod 'SigmobAd-iOS', '4.9.3'
  pod 'TradPlusAdSDK/GDTMobAdapter', '9.7.0'
  pod 'GDTMobSDK', '4.14.32'
  pod 'TradPlusAdSDK/PangleAdapter', '9.7.0'
  pod 'Ads-Global', '5.3.1.1'
  pod 'TradPlusAdSDK/TPCrossAdapter', '9.7.0'
  pod 'TradPlusAdSDK/CSJAdapter', '9.7.0'
  pod 'Ads-CN', '5.4.0.9'
  pod 'TradPlusAdSDK/BigoAdapter', '9.7.0'
  pod 'BigoADS','2.3.5'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
